### ISSUE TITLE
XDG vars not set

### ISSUE THREAD

**Issue by CyberShadow** [spanezz/nodm#1]
Hi,

When I use `nodm` on Arch Linux, the `XDG_...` variables are not set in the X session. I think this causes `systemctl --user` etc. to fail with "Failed to connect to bus: No such file or directory". `strace` shows that the error message comes from it trying to open `/sys/fs/kdbus/1000-user/bus`, and my kernel doesn't have kdbus. `ltrace` shows that it tries to read `XDG_RUNTIME_DIR` before accessing the `kdbus` path, which is not set in this situation. If I run `XDG_RUNTIME_DIR=/var/run/user/1000 systemctl --user status`, then the command works.

I.e.:

`sudo systemctl enable sddm && reboot`, start a terminal in X - XDG variables are there.
`sudo systemctl disable sddm && sudo systemctl enable nodm && reboot`, start a terminal in X - XDG variables are not there.

I understand that the variables are being set by [pam_systemd](https://www.freedesktop.org/software/systemd/man/pam_systemd.html), so it's not due to my `.xinitrc`.

Did I do something wrong, or..?

**Comment by CyberShadow** [comment]
I found a solution, not sure how correct it is, but `sudo cp /etc/pam.d/sddm /etc/pam.d/nodm` got the variables back. The file's contents is:

```
#%PAM-1.0

auth		include		system-login
account		include		system-login
password	include		system-login
session		include		system-login
```

**Comment by sunweaver** [comment]
Hi!

There is a debian/nodm.pam file that you should use also on non-Debian distros. Unfortunately, the nodm upstream project is rather Debian-centric. We are happy to receive a PR that moves the pam config file into the base folder and lets it be handled by Makefile.am.

Thanks+Greets,
Mike

**Comment by sunweaver** [comment]
Closing for now as the PAM file is provided (though not in a very maintainer friendly way for non-Debian maintainers).
