### ISSUE TITLE
PulseAudio won't start after autologin with nodm

### ISSUE THREAD

**Issue by kilbith** [spanezz/nodm#2]
Title says it all. I'm using Arch + i3.

**Comment by paulstelian97** [comment]
I always start pulseaudio manually in my .xinitrc script

**Comment by sunweaver** [comment]
pulseaudio startup is not the job of the display manager, but should be handled by the launched session manager. Thus closing this and tagging as invalid.

**Comment by kilbith** [comment]
We can autologin as well with a `agetty` service alone, and pulseaudio starts fine.

**Comment by sunweaver** [comment]
Hi kilbith

On  Mo 23 Jan 2017 13:49:37 CET, kilbith wrote:

> We can autologin as well with a `agetty` service alone, and  
> pulseaudio starts fine.

can you please provide more setup details and track down why  
pulseaudio gets started with agetty?

It is well possible, that systemd launched pulseaudio. There has just  
been a patch for nodm that adds systemd support.

Mike
-- 

DAS-NETZWERKTEAM
mike gabriel, herweg 7, 24357 fleckeby
mobile: +49 (1520) 1976 148
landline: +49 (4354) 8390 139

GnuPG Fingerprint: 9BFB AEE8 6C0A A5FF BF22  0782 9AF4 6B30 2577 1B31
mail: mike.gabriel@das-netzwerkteam.de, http://das-netzwerkteam.de

**Comment by kilbith** [comment]
If you want to test : 

```Bash
sudo mkdir /etc/systemd/system/getty@tty1.service.d/

sudo sh -c "cat >> /etc/systemd/system/getty@tty1.service.d/override.conf <<_EOF_
[Service]
ExecStart=
ExecStart=-/usr/bin/agetty --autologin $USER --noclear %I \$TERM
_EOF_"

cat >> ~/.bash_profile <<_EOF_
if [[ -z \$DISPLAY ]] && [[ \$(tty) = /dev/tty1 ]]; then exec startx; fi
_EOF_
```

Then of course disable `nodm` before rebooting.
